%YAML 1.0
---
#--------------------------------------------------------------------------------------------
# Map Parameters
#--------------------------------------------------------------------------------------------

# Map Parameters
Map.width: 100
Map.height: 100
Map.resolution: 0.05 # meter scale
Map.obstacle.padding: 5
Map.obstacle.connect_max: 15

Map.data.ball_track: 1
Map.data.ball: 2
Map.data.obstacle: 200
Map.data.obstacle.padding: 150

# RL Map Parameters
RL.Map.width: 31
RL.Map.height: 31
RL.Map.center: 15
RL.Map.resolution: 0.15 # meter scale
RL.Map.obstacle.padding: 5
RL.Map.obstacle.connect_max: 15

RL.Map.data.ball: 255
RL.Map.data.obstacle: 100
RL.Map.data.robot: 200
RL.Map.data.robot.padding: 150
