%YAML 1.0
---
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.width: 320
Camera.height: 240

Camera.fx: 298.31
Camera.fy: 297.69
Camera.cx: 161.66
Camera.cy: 121.68

Camera.k1: -0.095422
Camera.k2: 1.722925
Camera.p1: -0.003120
Camera.p2: 0.002098
Camera.k3: -4.87788

# Camera-Homography
Camera.H:
    [[-0.60496129,-3.55389713,7.42942965],
    [-7.0901749,0.12839407,-0.13872295],
    [0.18489881,19.03178138,1.0]]
