%YAML 1.0
---
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.width: 640
Camera.height: 360

Camera.fx: 506.745311
Camera.fy: 379.5
Camera.cx: 301.735270
Camera.cy: 168.8

Camera.k1: 0.096475
Camera.k2: -0.43515
Camera.p1: -0.00012
Camera.p2: 0.000968
Camera.k3: 0.851277

# Camera-Homography
Camera.H:
    [[0.0753429,-0.301418,0.581068],
    [-0.848973,-0.00387578,0.00624193],
    [0.20101,2.90698,1.0]]
