%YAML 1.0
---
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.width: 1280
Camera.height: 720

Camera.fx: 446.0
Camera.fy: 442.2
Camera.cx: 629.7
Camera.cy: 360.7

Camera.k1: 0.00876
Camera.k2: -0.04431
Camera.p1: -0.00630
Camera.p2: 0.000489
Camera.k3: 0.00830

# Camera-Homography
Camera.H:
    [[0.0753429,-0.301418,0.581068],
    [-0.848973,-0.00387578,0.00624193],
    [0.20101,2.90698,1.0]]
