(cl:defpackage tt_core_msgs-srv
  (:use )
  (:export
   "CAMERACROP"
   "<CAMERACROP-REQUEST>"
   "CAMERACROP-REQUEST"
   "<CAMERACROP-RESPONSE>"
   "CAMERACROP-RESPONSE"
   "CAMERAIMG"
   "<CAMERAIMG-REQUEST>"
   "CAMERAIMG-REQUEST"
   "<CAMERAIMG-RESPONSE>"
   "CAMERAIMG-RESPONSE"
   "MAPGENPOINT"
   "<MAPGENPOINT-REQUEST>"
   "MAPGENPOINT-REQUEST"
   "<MAPGENPOINT-RESPONSE>"
   "MAPGENPOINT-RESPONSE"
   "MOBILENETCROP"
   "<MOBILENETCROP-REQUEST>"
   "MOBILENETCROP-REQUEST"
   "<MOBILENETCROP-RESPONSE>"
   "MOBILENETCROP-RESPONSE"
  ))

