// Generated by gencpp from file tt_core_msgs/CameraCrop.msg
// DO NOT EDIT!


#ifndef TT_CORE_MSGS_MESSAGE_CAMERACROP_H
#define TT_CORE_MSGS_MESSAGE_CAMERACROP_H

#include <ros/service_traits.h>


#include <tt_core_msgs/CameraCropRequest.h>
#include <tt_core_msgs/CameraCropResponse.h>


namespace tt_core_msgs
{

struct CameraCrop
{

typedef CameraCropRequest Request;
typedef CameraCropResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraCrop
} // namespace tt_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tt_core_msgs::CameraCrop > {
  static const char* value()
  {
    return "c59f6f4ab593dbb46a0ee41e6151c029";
  }

  static const char* value(const ::tt_core_msgs::CameraCrop&) { return value(); }
};

template<>
struct DataType< ::tt_core_msgs::CameraCrop > {
  static const char* value()
  {
    return "tt_core_msgs/CameraCrop";
  }

  static const char* value(const ::tt_core_msgs::CameraCrop&) { return value(); }
};


// service_traits::MD5Sum< ::tt_core_msgs::CameraCropRequest> should match 
// service_traits::MD5Sum< ::tt_core_msgs::CameraCrop > 
template<>
struct MD5Sum< ::tt_core_msgs::CameraCropRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::CameraCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraCropRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::CameraCropRequest> should match 
// service_traits::DataType< ::tt_core_msgs::CameraCrop > 
template<>
struct DataType< ::tt_core_msgs::CameraCropRequest>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::CameraCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraCropRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tt_core_msgs::CameraCropResponse> should match 
// service_traits::MD5Sum< ::tt_core_msgs::CameraCrop > 
template<>
struct MD5Sum< ::tt_core_msgs::CameraCropResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::CameraCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraCropResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::CameraCropResponse> should match 
// service_traits::DataType< ::tt_core_msgs::CameraCrop > 
template<>
struct DataType< ::tt_core_msgs::CameraCropResponse>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::CameraCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraCropResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TT_CORE_MSGS_MESSAGE_CAMERACROP_H
