// Generated by gencpp from file tt_core_msgs/CameraImgRequest.msg
// DO NOT EDIT!


#ifndef TT_CORE_MSGS_MESSAGE_CAMERAIMGREQUEST_H
#define TT_CORE_MSGS_MESSAGE_CAMERAIMGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>

namespace tt_core_msgs
{
template <class ContainerAllocator>
struct CameraImgRequest_
{
  typedef CameraImgRequest_<ContainerAllocator> Type;

  CameraImgRequest_()
    : req()  {
    }
  CameraImgRequest_(const ContainerAllocator& _alloc)
    : req(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _req_type;
  _req_type req;





  typedef boost::shared_ptr< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraImgRequest_

typedef ::tt_core_msgs::CameraImgRequest_<std::allocator<void> > CameraImgRequest;

typedef boost::shared_ptr< ::tt_core_msgs::CameraImgRequest > CameraImgRequestPtr;
typedef boost::shared_ptr< ::tt_core_msgs::CameraImgRequest const> CameraImgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tt_core_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'tt_core_msgs': ['/home/naverlabs/ros/TT_final/src/tt3_common/tt_core_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f4c76065f5fb3257b999a50997b4d91";
  }

  static const char* value(const ::tt_core_msgs::CameraImgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f4c76065f5fb325ULL;
  static const uint64_t static_value2 = 0x7b999a50997b4d91ULL;
};

template<class ContainerAllocator>
struct DataType< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tt_core_msgs/CameraImgRequest";
  }

  static const char* value(const ::tt_core_msgs::CameraImgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32 req\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
";
  }

  static const char* value(const ::tt_core_msgs::CameraImgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraImgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tt_core_msgs::CameraImgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tt_core_msgs::CameraImgRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TT_CORE_MSGS_MESSAGE_CAMERAIMGREQUEST_H
