// Generated by gencpp from file tt_core_msgs/CameraImg.msg
// DO NOT EDIT!


#ifndef TT_CORE_MSGS_MESSAGE_CAMERAIMG_H
#define TT_CORE_MSGS_MESSAGE_CAMERAIMG_H

#include <ros/service_traits.h>


#include <tt_core_msgs/CameraImgRequest.h>
#include <tt_core_msgs/CameraImgResponse.h>


namespace tt_core_msgs
{

struct CameraImg
{

typedef CameraImgRequest Request;
typedef CameraImgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraImg
} // namespace tt_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tt_core_msgs::CameraImg > {
  static const char* value()
  {
    return "76e4e49f9c27975a034223a4d54fcbe4";
  }

  static const char* value(const ::tt_core_msgs::CameraImg&) { return value(); }
};

template<>
struct DataType< ::tt_core_msgs::CameraImg > {
  static const char* value()
  {
    return "tt_core_msgs/CameraImg";
  }

  static const char* value(const ::tt_core_msgs::CameraImg&) { return value(); }
};


// service_traits::MD5Sum< ::tt_core_msgs::CameraImgRequest> should match 
// service_traits::MD5Sum< ::tt_core_msgs::CameraImg > 
template<>
struct MD5Sum< ::tt_core_msgs::CameraImgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::CameraImg >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraImgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::CameraImgRequest> should match 
// service_traits::DataType< ::tt_core_msgs::CameraImg > 
template<>
struct DataType< ::tt_core_msgs::CameraImgRequest>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::CameraImg >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraImgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tt_core_msgs::CameraImgResponse> should match 
// service_traits::MD5Sum< ::tt_core_msgs::CameraImg > 
template<>
struct MD5Sum< ::tt_core_msgs::CameraImgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::CameraImg >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraImgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::CameraImgResponse> should match 
// service_traits::DataType< ::tt_core_msgs::CameraImg > 
template<>
struct DataType< ::tt_core_msgs::CameraImgResponse>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::CameraImg >::value();
  }
  static const char* value(const ::tt_core_msgs::CameraImgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TT_CORE_MSGS_MESSAGE_CAMERAIMG_H
