// Generated by gencpp from file tt_core_msgs/MapGenPoint.msg
// DO NOT EDIT!


#ifndef TT_CORE_MSGS_MESSAGE_MAPGENPOINT_H
#define TT_CORE_MSGS_MESSAGE_MAPGENPOINT_H

#include <ros/service_traits.h>


#include <tt_core_msgs/MapGenPointRequest.h>
#include <tt_core_msgs/MapGenPointResponse.h>


namespace tt_core_msgs
{

struct MapGenPoint
{

typedef MapGenPointRequest Request;
typedef MapGenPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapGenPoint
} // namespace tt_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tt_core_msgs::MapGenPoint > {
  static const char* value()
  {
    return "77e9b44efbf859a31c896f22a0604ab1";
  }

  static const char* value(const ::tt_core_msgs::MapGenPoint&) { return value(); }
};

template<>
struct DataType< ::tt_core_msgs::MapGenPoint > {
  static const char* value()
  {
    return "tt_core_msgs/MapGenPoint";
  }

  static const char* value(const ::tt_core_msgs::MapGenPoint&) { return value(); }
};


// service_traits::MD5Sum< ::tt_core_msgs::MapGenPointRequest> should match 
// service_traits::MD5Sum< ::tt_core_msgs::MapGenPoint > 
template<>
struct MD5Sum< ::tt_core_msgs::MapGenPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::MapGenPoint >::value();
  }
  static const char* value(const ::tt_core_msgs::MapGenPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::MapGenPointRequest> should match 
// service_traits::DataType< ::tt_core_msgs::MapGenPoint > 
template<>
struct DataType< ::tt_core_msgs::MapGenPointRequest>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::MapGenPoint >::value();
  }
  static const char* value(const ::tt_core_msgs::MapGenPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tt_core_msgs::MapGenPointResponse> should match 
// service_traits::MD5Sum< ::tt_core_msgs::MapGenPoint > 
template<>
struct MD5Sum< ::tt_core_msgs::MapGenPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::MapGenPoint >::value();
  }
  static const char* value(const ::tt_core_msgs::MapGenPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::MapGenPointResponse> should match 
// service_traits::DataType< ::tt_core_msgs::MapGenPoint > 
template<>
struct DataType< ::tt_core_msgs::MapGenPointResponse>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::MapGenPoint >::value();
  }
  static const char* value(const ::tt_core_msgs::MapGenPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TT_CORE_MSGS_MESSAGE_MAPGENPOINT_H
