// Generated by gencpp from file tt_core_msgs/MobileNetCrop.msg
// DO NOT EDIT!


#ifndef TT_CORE_MSGS_MESSAGE_MOBILENETCROP_H
#define TT_CORE_MSGS_MESSAGE_MOBILENETCROP_H

#include <ros/service_traits.h>


#include <tt_core_msgs/MobileNetCropRequest.h>
#include <tt_core_msgs/MobileNetCropResponse.h>


namespace tt_core_msgs
{

struct MobileNetCrop
{

typedef MobileNetCropRequest Request;
typedef MobileNetCropResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MobileNetCrop
} // namespace tt_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tt_core_msgs::MobileNetCrop > {
  static const char* value()
  {
    return "ce138e689a8c9d31419375ee3f1679a9";
  }

  static const char* value(const ::tt_core_msgs::MobileNetCrop&) { return value(); }
};

template<>
struct DataType< ::tt_core_msgs::MobileNetCrop > {
  static const char* value()
  {
    return "tt_core_msgs/MobileNetCrop";
  }

  static const char* value(const ::tt_core_msgs::MobileNetCrop&) { return value(); }
};


// service_traits::MD5Sum< ::tt_core_msgs::MobileNetCropRequest> should match 
// service_traits::MD5Sum< ::tt_core_msgs::MobileNetCrop > 
template<>
struct MD5Sum< ::tt_core_msgs::MobileNetCropRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::MobileNetCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::MobileNetCropRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::MobileNetCropRequest> should match 
// service_traits::DataType< ::tt_core_msgs::MobileNetCrop > 
template<>
struct DataType< ::tt_core_msgs::MobileNetCropRequest>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::MobileNetCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::MobileNetCropRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tt_core_msgs::MobileNetCropResponse> should match 
// service_traits::MD5Sum< ::tt_core_msgs::MobileNetCrop > 
template<>
struct MD5Sum< ::tt_core_msgs::MobileNetCropResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tt_core_msgs::MobileNetCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::MobileNetCropResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tt_core_msgs::MobileNetCropResponse> should match 
// service_traits::DataType< ::tt_core_msgs::MobileNetCrop > 
template<>
struct DataType< ::tt_core_msgs::MobileNetCropResponse>
{
  static const char* value()
  {
    return DataType< ::tt_core_msgs::MobileNetCrop >::value();
  }
  static const char* value(const ::tt_core_msgs::MobileNetCropResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TT_CORE_MSGS_MESSAGE_MOBILENETCROP_H
